config/routes.rb
Rails.application.routes.draw do
  resources :posts
  devise_for :users
  root 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  validates :date, :rationale, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :first_name, :last_name, presence: true

  def full_name
    last_name.upcase + ', ' + first_name.upcase
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :find_post, only: %i[show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to @post, notice: 'Your post was created successfully'
    else
      render :new
    end
  end

  def show; end

  private

  def post_params
    params.require(:post).permit(:date, :rationale)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    'active' if current_page?(path)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Overtime
    = csrf_meta_tags
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container
      .row
        .col-md-12
          = render 'shared/nav'
          = yield

app/views/posts/_post.html.haml
%tr
  %td
    = post.id
  %td
    = post.date
  %td
    = post.user.full_name
  %td
    = truncate(post.rationale)

app/views/posts/index.html.haml
%h1 Posts
%table.table.table-striped.table-hover
  %thead
    %tr
      %th #
      %th Date
      %th User
      %th Rationale
  %tbody
    = render @posts

app/views/posts/new.html.haml
= form_for(@post) do |f|
  = f.date_field :date
  = f.text_area :rationale

  = f.submit 'Save'

app/views/posts/show.html.haml
= @post.inspect

app/views/shared/_nav.html.haml
.logo
  %h1 Time Tracker
%ul.custom-nav.nav.nav-tabs
  %li{class: "#{active?(root_path)}"}
    = link_to 'Home', root_path
  %li{class: "#{active?(posts_path)}"}
    = link_to 'Time entries', posts_path
  %li.dropdown.pull-right
    %a.dropdown-toggle{href: '#', data: {toggle: 'dropdown'}} Account
    %ul.dropdown-menu
      %li
        = link_to 'Edit details', edit_user_registration_path
      %li.divider
      %li
        = link_to 'Logout', destroy_user_session_path, method: :delete